### ISSUE TITLE
how to install from private PyPI server.

### ISSUE THREAD

**Issue by bzd111** [mitsuhiko/rye#120]
I want to install a package from my PyPI server, but I have noticed that the [code](https://github.com/mitsuhiko/rye/blob/45818e01c99105b18347d618a9d1b1ad05489ee6/rye/src/cli/add.rs#L17)  only searches for packages on https://pypi.org/simple/. 
I suggest that we configure the index_urls and trusted-host settings in the pyproject.toml file, for example:

```toml
[config.rye.pip]
index-urls=["http://192.168.x.x:3141/root/dev/+simple/"]
trusted-hosts=["192.168.x.x"]
```
