### ISSUE TITLE
Large scale dependency exclusion

### ISSUE THREAD

**Issue by Immortalin** [mitsuhiko/rye#230]
When installing [encodec](https://github.com/facebookresearch/encodec/blob/2d29d9353c2ff0ab1aeadc6a3d439854ee77da3e/setup.py#L50), I wanted to install it in CPU-only mode due to lack of an `nvidia` processor on my local machine. It required going through the generated lock file and manually excluding around 10 nvidia dependencies, even when custom indices have been added. The indice resolution should happen before the dependency locking step.

```toml
dependencies = ["encodec~=0.1.1", "torch~=2.0.1", "torchvision~=0.15.2", "torchaudio~=2.0.2"]
readme = "README.md"
requires-python = ">= 3.8"

[[tool.rye.sources]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
type = "find-links"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = ["black~=23.3.0", "ruff~=0.0.270"]
excluded-dependencies = ["nvidia-cublas-cu11", "nvidia-cuda-cupti-cu11", "nvidia-cuda-nvrtc-cu11", "nvidia-cuda-runtime-cu11", "nvidia-cudnn-cu11", "nvidia-cufft-cu11", "nvidia-curand-cu11", "nvidia-cusolver-cu11", "nvidia-cusparse-cu11", "nvidia-nccl-cu11", "nvidia-nvtx-cu11"]
[tool.hatch.metadata]
allow-direct-references = true
```
![image](https://github.com/mitsuhiko/rye/assets/7126128/6e5a88cd-e02c-4a9b-85fa-d9431987b17b)
