### ISSUE TITLE
Format project dependencies in `pyproject.toml`

### ISSUE THREAD

**Issue by maekawatoshiki** [mitsuhiko/rye#261]
### Summary

- Currently, it seems `project.dependencies` is not formatted (in a readable way).
  - Particularly, when there are many dependencies, the code width often exceeds 80 characters, which is far too wide.
- I'd like the dependencies to be formatted, for example, when `rye add` is used.

```toml:pyproject.toml
[project]
# before
dependencies = ["pip~=23.1.2", "matplotlib==3.5.2", "Pillow==9.2.0", "torchvision==0.13.0", "torch==1.12.0", "pytest~=7.3.1", "pytest-xdist~=3.2.1", "onnxruntime==1.13.1", "onnx==1.12.0", "transformers[onnx]~=4.28.1", "onnxsim==0.4.17", "numpy==1.22.3"]
# after
dependencies = ["pip~=23.1.2",
    "matplotlib==3.5.2",
    "Pillow==9.2.0",
    "torchvision==0.13.0",
    "torch==1.12.0",
    "pytest~=7.3.1",
    "pytest-xdist~=3.2.1",
    "onnxruntime==1.13.1",
    "onnx==1.12.0",
    "transformers[onnx]~=4.28.1",
    "onnxsim==0.4.17",
    "numpy==1.22.3"
]
```
