### ISSUE TITLE
Bump dynamic version adds the new version to pyproject.toml

### ISSUE THREAD

**Issue by mrkbac** [mitsuhiko/rye#399]
### Steps to Reproduce

pyproject.toml
```toml
[project]
name = "test"
requires-python = ">= 3.10"

dynamic = ["version"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true

[tool.hatch.version]
path = "src/test/__init__.py"
```

__init__.py
```python
__version__ = "1.2.3"
```

### Expected Result

When executing `rye verion --bump major` I epected that the version in `__init__.py` is updated

### Actual Result

Executing `rye version --bump major` results in an updated of the `pyptoject.toml`

```toml
[project]
name = "test"
requires-python = ">= 3.10"

dynamic = ["version"]
version = "2.2.3"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true

[tool.hatch.version]
path = "src/test/__init__.py"
```

### Version Info

rye 0.11.0
commit: 0.11.0 (f6f63d6c1 2023-07-18)
platform: macos (aarch64)
self-python: cpython@3.11
symlink support: true
