### ISSUE TITLE
I cannot install pylint after setting config.toml

### ISSUE THREAD

**Issue by makinzm** [mitsuhiko/rye#445]
### Steps to Reproduce

1. Set `.rye/config.toml` like that: https://rye-up.com/guide/config/
2. Just command `rye install pylint`

### Expected Result

Install correctly.

### Actual Result

```rust
Looking in indexes: http://pypi.org/simple/
WARNING: The repository located at pypi.org is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.org'.
ERROR: Could not find a version that satisfies the requirement pylint (from versions: none)
ERROR: No matching distribution found for pylint
error: tool installation failed
```

### Version Info

```zsh
╰─ rye --version                                                                                                                     ─╯
rye 0.13.0
commit: 0.13.0 (8e011231e 2023-08-29)
platform: macos (x86_64)
self-python: cpython@3.11
symlink support: true
```

### Stacktrace

I think [source] in my `config.toml` caused this problem (referring to https://rye-up.com/guide/config/):

I'm not sure how to fix this.

```toml
[default]
# This is the default value that is written into new pyproject.toml
# files for the `project.requires-python` key
requires-python = ">= 3.8"

# This is the default toolchain that is used
toolchain = "cpython@3.11.1"

# This is the default build system that is used
build-system = "hatchling"

# This is the default license that is used
license = "MIT"

# This sets the default author (overrides the defaults from git).  The
# format here is "Name <email>".
author = "makinzm <**@**.**>"

# The dependency operator to use by default for dependencies.  The options are
# '>=', '~=', and '=='.  The default currently is '>='.  This affects the behavior
# of `rye add`.
dependency-operator = ">="

# [proxy]
# the proxy to use for HTTP (overridden by the http_proxy environment variable)
http = "http://127.0.0.1:4000"
# the proxy to use for HTTPS (overridden by the https_proxy environment variable)
https = "http://127.0.0.1:4000"

[behavior]
# When set to true the `managed` flag is always assumed to be true.
force-rye-managed = false

# Enables global shims when set to `true`.  This means that the installed
# `python` shim will resolve to a Rye managed toolchain even outside of
# virtual environments.
global-python = false

# a array of tables with optional sources.  Same format as in pyproject.toml
[[sources]]
name = "default"
url = "http://pypi.org/simple/"

```
