### ISSUE TITLE
Instructions for installing PyTorch

### ISSUE THREAD

**Issue by Nugine** [mitsuhiko/rye#460]
1. How to add PyTorch dependencies?
2. How to automatically install different wheels for different platform?
3. How to avoid keeping a redundant copy for every project if they are using the same version?

Related:
+ https://github.com/python-poetry/poetry/issues/6409

**Comment by WilianZilv** [comment]
By following this guide we can do the following:
https://github.com/mitsuhiko/rye/blob/3cbfdf3363e7df7058b753c831d9b09d1a503833/docs/guide/sources.md

add this at the end of your pyproject.toml (i'm using the cpu version for this example)

```toml
[[tool.rye.sources]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
```

run the commands
```bash
rye add torch torchvision torchaudio
rye sync
```
