### ISSUE TITLE
editable dev dependency

### ISSUE THREAD

**Issue by T-256** [mitsuhiko/rye#482]
similar to [PDM](https://pdm.fming.dev/latest/usage/dependency/#editable-dependencies): 
```toml
[tool.rye]
dev-dependencies = [
    "-e file:///path/to/project#egg=project",
]
```
