### ISSUE TITLE
`rye sync --update=pkg` silently does nothing if `pkg` is pinned in the pyproject.toml config

### ISSUE THREAD

**Issue by RobertCraigie** [mitsuhiko/rye#514]
### Steps to Reproduce

Config like this
```toml
[tool.rye]
managed = true
dev-dependencies = [
  "pyright==1.1.338",
]
```
Running `rye sync --update=pyright` will not do anything.

### Expected Result

A warning / error message that says the version is pinned in the config so it can't be updated.

### Actual Result

No changes, no warning output.

### Version Info

```
rye 0.15.2
commit: 0.15.2 (e2beb3a90 2023-10-04)
platform: macos (aarch64)
self-python: cpython@3.11
symlink support: true
```
