### ISSUE TITLE
Allow shell expantion/interpolation in rye run command

### ISSUE THREAD

**Issue by dvonessen** [mitsuhiko/rye#695]
Hi,

I asked this question in the discord, but thought about it. 
At the moment it is not possible to use shell interpolation with `rye run` command.
See: https://rye-up.com/guide/pyproject/#cmd

It would be awesome if that would be made possible. 
`pdm` does seem to have this ability. 
See: https://pdm-project.org/latest/usage/scripts/#shell

Example:
```toml
...
[tool.rye.scripts]
test_script = {shell="echo $TEST_ENV"}
```
```shell
> export TEST_ENV="FooBar"
> rye run test_script
$TEST_ENV
```
